when@dev: &dev
    nelmio_alice:
        locale: 'en_US' # Default locale for the Faker Generator
        seed: 1 # Value used to make sure Faker generates data consistently across
            # runs, set to null to disable.
        functions_blacklist:
            - 'current'
            - 'shuffle'
            - 'date'
            - 'time'
            - 'file'
            - 'md5'
            - 'sha1'

when@test: *dev
