version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
###< doctrine/doctrine-bundle ###
  php:
      container_name: php
      build:
        context: ./php
      ports:
        - '9000:9000'
      volumes:
        - .:/var/www
        - ./php/mysql-config.yml:/etc/newrelic-infra/integrations.d/mysql-config.yml
      depends_on:
        - database
  
  newrelic:
    container_name: newrelic-infra
    build:
      context: ./newrelic
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "//var//run//docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  nginx:
      container_name: nginx
      image: nginx:stable-alpine
      ports:
        - '8080:80'
      volumes:
        - .:/var/www
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - database
  phpmyadmin:
        depends_on:
          - database
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
          PMA_HOST: database
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - "8088:80"
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
